/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  safelist: [
    { pattern: /(bg|text|stroke|border|shadow)-(primary|secondary|error|tertiary)(\/10|\/20|\/30|\/40|\/50)?/ },
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#ffb95f',
        'on-primary-container': '#dad7ff',
        'primary-fixed-dim': '#c3c0ff',
        'on-surface': '#dae2fd',
        'surface-container-high': '#222a3d',
        'surface-variant': '#2d3449',
        'on-tertiary': '#472a00',
        'inverse-on-surface': '#283044',
        'tertiary-fixed': '#ffddb8',
        'error-container': '#93000a',
        'secondary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#2a1700',
        'on-error': '#690005',
        'surface-container-lowest': '#060e20',
        'inverse-primary': '#4d44e3',
        'on-tertiary-container': '#ffd4a4',
        'on-tertiary-fixed-variant': '#653e00',
        'secondary-fixed': '#6ffbbe',
        'surface-dim': '#0b1326',
        'surface-container': '#171f33',
        'inverse-surface': '#dae2fd',
        'surface-container-highest': '#2d3449',
        'outline-variant': '#464555',
        background: '#0b1326',
        error: '#ffb4ab',
        'on-primary': '#1d00a5',
        'on-primary-fixed': '#0f0069',
        'on-secondary-fixed': '#002113',
        'on-secondary-container': '#00311f',
        'secondary-container': '#00a572',
        'on-surface-variant': '#c7c4d8',
        'primary-fixed': '#e2dfff',
        secondary: '#4edea3',
        tertiary: '#ffb95f',
        'primary-container': '#4f46e5',
        'on-background': '#dae2fd',
        surface: '#0b1326',
        'on-secondary': '#003824',
        'on-secondary-fixed-variant': '#005236',
        'surface-container-low': '#131b2e',
        outline: '#918fa1',
        'surface-bright': '#31394d',
        'on-primary-fixed-variant': '#3323cc',
        'surface-tint': '#c3c0ff',
        primary: '#c3c0ff',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      keyframes: {
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
      },
      animation: {
        shimmer: 'shimmer 3s linear infinite',
      },
    },
  },
};
